---
- name: Remove legacy sources.list file
  ansible.builtin.file:
    path: /etc/apt/sources.list
    state: absent

- name: Add custom sources file
  template:
    src: apt/debian.sources.j2
    dest: /etc/apt/sources.list.d/debian.sources
    owner: root
    group: root
    mode: '0644'
  notify: update apt cache

- name: Update APT cache
  meta: flush_handlers
