- name: Installing wget
  apt:
    name: wget
    state: present

- name: Add VSCodium key
  shell: wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | gpg --dearmor | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg

- name: Adding VSCodium repository
  copy:
    src: files/vscodium/vscodium.sources
    dest: /etc/apt/sources.list.d/vscodium.sources
    owner: root
    group: root
    mode: '0644'
  notify: update apt cache

- name: Remove legacy VSCodium sources.list file
  file:
    path: /etc/apt/sources.list.d/vscodium.list
    state: absent
  notify: update apt cache

- name: Update APT cache
  meta: flush_handlers

- name: Installing VSCodium
  apt:
    name: codium
    state: present